--Hangi þehrin ne kadarlýk satýþ yaptýðý bilgisi
SELECT CITY,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS
GROUP BY CITY
ORDER BY CITY ASC

--Þehirlerin aylara göre yaptýðý toplam  satýþ miktarý
SELECT CITY,MONTH_,SUM(LINETOTAL) as TOTALSALE FROM SALEORDERS
GROUP BY MONTH_,CITY
ORDER BY CITY,MONTH_ ASC

--Þehirler en çok hangi günde satýþ yapmýþ
SELECT CITY,DAYOFWEEK_,SUM(LINETOTAL) as TOTALSALE FROM SALEORDERS
GROUP BY DAYOFWEEK_,CITY
ORDER BY CITY,DAYOFWEEK_ ASC

--Þehirlerin günlere göre yaptýðý total satýþ 
--Alias kullanmayý unutma çünkü GROUP BY ile deðil Alias ile S dediðimiz SALEORDERS 
--tablosundan gelen CITY deðerini where koþulu içine koyarak bizim totalini 
--bulmuþ olduðumuz þehir ile denkledik bu sayede aslýnda gruplamýþ gibi olduk
--Yani bize dönen her þehir için 7 sütun deðerini de bulduðumuz bir satýr oluþturduk
SELECT DISTINCT(CITY),
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_ = '01.PZT' ) 
AS PAZARTESÝ,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_ = '02.SAL') 
AS SALI,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_ = '03.ÇAR') 
AS ÇARÞAMBA,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_ = '04.PER') 
AS PERÞEMBE,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_ = '05.CUM') 
AS CUMA,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_ = '06.CMT') 
AS CUMARTESÝ,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_ = '07.PAZ') 
AS PAZAR
FROM SALEORDERS S
ORDER BY S.CITY 



select * from SALEORDERS

SELECT * FROM SALEORDERS